# Generated by Django 4.1.7 on 2023-03-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_active',
            field=models.DateTimeField(null=True),
        ),
    ]
