# Generated by Django 4.0.3 on 2022-10-30 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ozp',
            name='do_foto',
        ),
        migrations.RemoveField(
            model_name='ozp',
            name='posle_foto',
        ),
    ]
