# Generated by Django 4.0.3 on 2022-11-12 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ozp_foto_zamechania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ozp',
            name='foto_zamechania',
            field=models.ImageField(blank=True, null=True, upload_to='img/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.png', '.jpg', '.jpeg', '.tiff', '.bmp', '.gif'], message='Тип файла выбран неверно. Выберите файл изображения.')]),
        ),
    ]
