# Generated by Django 4.0.3 on 2022-11-12 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_ozp_foto_zamechania'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ozp',
            name='foto_zamechania',
        ),
        migrations.AlterField(
            model_name='foto_zamechanya',
            name='zamechanie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_zamechania', to='main.ozp'),
        ),
    ]
