# Generated by Django 4.0.3 on 2022-11-12 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_ozp_foto_zamechania_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ozp',
            name='object_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='main.object'),
        ),
    ]
