# Generated by Django 4.0.3 on 2022-11-12 17:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_alter_ozp_object_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto_zamechanya',
            name='foto',
            field=models.ImageField(upload_to='img/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.png', '.jpeg', '.tiff', '.bmp', '.gif'], message='Тип файла выбран неверно. Выберите файл изображения.')]),
        ),
        migrations.CreateModel(
            name='Podano_na_vipolnenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podano', models.BooleanField(default=False)),
                ('time_podano', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('zamechanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ozp')),
            ],
        ),
    ]
