# Generated by Django 4.0.3 on 2022-11-12 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_foto_zamechanya_foto_podano_na_vipolnenie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podano_na_vipolnenie',
            name='zamechanie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.ozp'),
        ),
    ]
