# Generated by Django 4.0.3 on 2022-11-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_podano_na_vipolnenie_otklonit_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podano_na_vipolnenie',
            name='otklonit_comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
