# Generated by Django 4.1.7 on 2023-03-12 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0002_remove_inventory_mol'),
        ('main', '0011_alter_department_ceh_alter_department_uchastok'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
