# Generated by Django 4.1.7 on 2023-05-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_department_ceh_alter_department_uchastok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_prod',
            field=models.BooleanField(default=False),
        ),
    ]
