# Generated by Django 4.1.7 on 2023-05-28 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_position_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ozp',
            name='object_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ozp', to='main.object'),
        ),
    ]
