# Generated by Django 4.1.7 on 2023-06-02 09:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_technicheskie_usloviya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicheskie_usloviya',
            name='date',
            field=models.DateField(verbose_name='Укажите дату технических условий'),
        ),
        migrations.AlterField(
            model_name='technicheskie_usloviya',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Напишите краткое описание технических условий'),
        ),
        migrations.AlterField(
            model_name='technicheskie_usloviya',
            name='doc',
            field=models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'tiff', 'bmp', 'gif', 'pdf', 'doc', 'docx'], message='Тип файла выбран неверно.')], verbose_name='Загрузите копию технических условий'),
        ),
        migrations.AlterField(
            model_name='technicheskie_usloviya',
            name='expire_date',
            field=models.DateField(verbose_name='Укажите дату окончания действия технических условий'),
        ),
        migrations.AlterField(
            model_name='technicheskie_usloviya',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Укажите наименование документа'),
        ),
        migrations.AlterField(
            model_name='technicheskie_usloviya',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.object', verbose_name='Выберите объект технических условий'),
        ),
        migrations.AlterField(
            model_name='technicheskie_usloviya',
            name='organization',
            field=models.CharField(max_length=100, verbose_name='Укажите организацию которой выданы ТУ'),
        ),
        migrations.AlterField(
            model_name='technicheskie_usloviya',
            name='proekt',
            field=models.CharField(max_length=150, verbose_name='Укажите наименование проекта'),
        ),
    ]
