# Generated by Django 4.1.7 on 2023-06-02 14:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_technicheskie_usloviya_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto_zamechanya',
            name='foto',
            field=models.ImageField(upload_to='img/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.png', '.jpeg', '.tiff', '.bmp', '.gif', 'jpg'], message='Тип файла выбран неверно. Выберите файл изображения.')]),
        ),
        migrations.AlterField(
            model_name='technicheskaya_documentacia',
            name='doc',
            field=models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'tiff', 'bmp', 'gif', 'pdf', 'doc', 'docx', 'jpg'], message='Тип файла выбран неверно.')], verbose_name='Загрузите документ'),
        ),
        migrations.AlterField(
            model_name='technicheskie_usloviya',
            name='doc',
            field=models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'tiff', 'bmp', 'gif', 'pdf', 'doc', 'docx', 'jpg'], message='Тип файла выбран неверно.')], verbose_name='Загрузите копию технических условий'),
        ),
        migrations.CreateModel(
            name='Sheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Укажите наименование схемы')),
                ('doc', models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'tiff', 'bmp', 'gif', 'pdf', 'doc', 'docx', 'jpg', 'vsd', 'vsdx', 'vdx'], message='Тип файла выбран неверно.')], verbose_name='Загрузите схему')),
                ('date', models.DateField(verbose_name='Укажите дату документа')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='scheme', to='main.object', verbose_name='Выберите объект')),
            ],
        ),
    ]
