# Generated by Django 4.1.7 on 2023-06-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_foto_zamechanya_foto_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sheme',
            new_name='Scheme',
        ),
    ]
