# Generated by Django 4.1.7 on 2023-06-03 08:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_sheme_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='object_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Наименование станции'),
        ),
        migrations.AlterField(
            model_name='object',
            name='rrl_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.rrlline', verbose_name='Наименование линии связи'),
        ),
        migrations.AlterField(
            model_name='object',
            name='uchastok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.department', verbose_name='Участок связи'),
        ),
        migrations.AlterField(
            model_name='position',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='position',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Район'),
        ),
        migrations.CreateModel(
            name='Object_Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_name', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'tiff', 'bmp', 'gif', 'jpg'], message='Тип файла выбран неверно.')], verbose_name='Выберите фотографию АМС')),
                ('year', models.DateField(default=None, verbose_name='Укажите ориентировочную дату фото')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='main.object')),
            ],
        ),
    ]
