# Generated by Django 4.1.7 on 2023-06-04 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_object_object_name_alter_object_rrl_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='latitude_degrees',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Значение градусов не может быть отрицательным'), django.core.validators.MaxValueValidator(180, message='Значение градусов не может быть больше 180')], verbose_name='°'),
        ),
        migrations.AlterField(
            model_name='position',
            name='latitude_minutes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Значение минут не может быть отрицательным'), django.core.validators.MaxValueValidator(60, message='Значение минут не может быть больше 60')], verbose_name="'"),
        ),
        migrations.AlterField(
            model_name='position',
            name='latitude_seconds',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, message='Значение секунд не может быть отрицательным'), django.core.validators.MaxValueValidator(60, message='Значение секунд не может быть больше 60')], verbose_name='"'),
        ),
        migrations.AlterField(
            model_name='position',
            name='longitude_degrees',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Значение градусов не может быть отрицательным'), django.core.validators.MaxValueValidator(180, message='Значение градусов не может быть больше 180')], verbose_name='°'),
        ),
        migrations.AlterField(
            model_name='position',
            name='longitude_minutes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Значение минут не может быть отрицательным'), django.core.validators.MaxValueValidator(60, message='Значение минут не может быть больше 60')], verbose_name="'"),
        ),
        migrations.AlterField(
            model_name='position',
            name='longitude_seconds',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, message='Значение секунд не может быть отрицательным'), django.core.validators.MaxValueValidator(60, message='Значение секунд не может быть больше 60')], verbose_name='"'),
        ),
    ]
