# Generated by Django 4.1.7 on 2023-06-04 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_position_latitude_degrees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object_foto',
            name='foto_name',
        ),
    ]
