# Generated by Django 4.1.7 on 2023-06-04 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_object_foto_foto_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='owner',
            field=models.CharField(default='ПАО "Газпром"', max_length=50, verbose_name='Организация - владелец объекта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='object_foto',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='main.object', verbose_name='Выберите объект изображенный на фотографии'),
        ),
    ]
