# Generated by Django 4.1.7 on 2023-06-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_object_owner_alter_object_foto_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='owner',
        ),
    ]
