# Generated by Django 4.0.3 on 2022-10-30 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.object')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentation', models.FileField(upload_to='media')),
                ('year', models.DateField()),
                ('organization_name', models.CharField(max_length=50)),
                ('project_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.ams')),
            ],
        ),
        migrations.CreateModel(
            name='Measurments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('results', models.IntegerField()),
                ('protocol_pdf', models.FileField(upload_to='media')),
                ('measurment_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.ams')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.IntegerField()),
                ('inventory_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('inventory_ams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.ams')),
                ('mol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FileField(upload_to='media')),
                ('year', models.DateField(default=None)),
                ('diagnostic_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.ams')),
            ],
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('type', models.CharField(max_length=30)),
                ('date_birth', models.DateField()),
                ('character_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.ams')),
            ],
        ),
    ]
