# Generated by Django 4.1.7 on 2023-04-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0002_remove_inventory_mol'),
    ]

    operations = [
        migrations.AddField(
            model_name='ams',
            name='date_birth',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ams',
            name='height',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ams',
            name='scheme',
            field=models.FileField(default=None, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ams',
            name='type',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ams',
            name='weight',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='owner',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Characteristic',
        ),
    ]
