# Generated by Django 4.1.7 on 2023-04-01 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ams', '0003_ams_date_birth_ams_height_ams_scheme_ams_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ams',
            name='is_dangerous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ams',
            name='otjazhki',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ams',
            name='otjazhki_count',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ams',
            name='responsive_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Sez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sez_protocol', models.FileField(upload_to='media')),
                ('year', models.DateField(default=None)),
                ('sez_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.ams')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentation', models.FileField(upload_to='media')),
                ('year', models.DateField()),
                ('passport_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.ams')),
            ],
        ),
    ]
