# Generated by Django 4.1.7 on 2023-04-01 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0004_ams_is_dangerous_ams_otjazhki_ams_otjazhki_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ams',
            name='type',
            field=models.CharField(choices=[('Башня', 'Башня'), ('Мачта', 'Мачта')], max_length=30),
        ),
        migrations.CreateModel(
            name='Foto_Ams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_name', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='media')),
                ('year', models.DateField(default=None)),
                ('foto_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.ams')),
            ],
        ),
    ]
