# Generated by Django 4.1.7 on 2023-04-02 16:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_alter_department_ceh_alter_department_uchastok_and_more'),
        ('ams', '0005_alter_ams_type_foto_ams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ams',
            name='date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Укажите дату ввода АМС в эксплуатацию'),
        ),
        migrations.AlterField(
            model_name='ams',
            name='height',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным'), django.core.validators.MaxValueValidator(250, message='Значение не может быть больше 250')], verbose_name='Укажите высоту АМС, м'),
        ),
        migrations.AlterField(
            model_name='ams',
            name='object_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.object', verbose_name='Выберите объект'),
        ),
        migrations.AlterField(
            model_name='ams',
            name='otjazhki_count',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='Укажите количество оттяжек'),
        ),
        migrations.AlterField(
            model_name='ams',
            name='responsive_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Выберите ответственного за эксплуатацию'),
        ),
        migrations.AlterField(
            model_name='ams',
            name='scheme',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='Схема АМС'),
        ),
        migrations.AlterField(
            model_name='ams',
            name='type',
            field=models.CharField(choices=[('Башня', 'Башня'), ('Мачта', 'Мачта'), ('Трубостойка', 'Трубостойка')], max_length=30, null=True, verbose_name='Выберите тип АМС'),
        ),
        migrations.AlterField(
            model_name='ams',
            name='weight',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным'), django.core.validators.MaxValueValidator(250, message='Значение не может быть больше 250')], verbose_name='Укажите вес АМС, т'),
        ),
    ]
