# Generated by Django 4.1.7 on 2023-04-02 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0006_alter_ams_date_birth_alter_ams_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='diagnostic_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic', to='ams.ams'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='ams.ams'),
        ),
    ]
