# Generated by Django 4.1.7 on 2023-04-02 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0007_alter_diagnostic_diagnostic_instance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurments',
            name='measurment_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol', to='ams.ams'),
        ),
    ]
