# Generated by Django 4.1.7 on 2023-04-02 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0008_alter_measurments_measurment_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto_ams',
            name='foto_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='ams.ams'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='passport_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='ams.ams'),
        ),
        migrations.AlterField(
            model_name='sez',
            name='sez_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sez', to='ams.ams'),
        ),
    ]
