# Generated by Django 4.1.7 on 2023-04-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0009_alter_foto_ams_foto_instance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ams',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='Паспорт АМС'),
        ),
        migrations.DeleteModel(
            name='Passport',
        ),
    ]
