# Generated by Django 4.1.7 on 2023-04-16 10:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0010_ams_passport_delete_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ams',
            name='otjazhki_count',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='Укажите количество ярусов оттяжек'),
        ),
        migrations.AlterField(
            model_name='ams',
            name='scheme',
            field=models.FileField(blank=True, null=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'tiff', 'bmp', 'gif', 'pdf', 'vsd', 'vsdx'], message='Тип файла выбран неверно.')], verbose_name='Выберите схему АМС'),
        ),
        migrations.AlterField(
            model_name='ams',
            name='weight',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным'), django.core.validators.MaxValueValidator(1000, message='Значение не может быть больше 1000')], verbose_name='Укажите вес АМС, т'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_ams',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='ams.ams'),
        ),
    ]
