# Generated by Django 4.1.7 on 2023-04-23 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0013_alter_diagnostic_result_alter_diagnostic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='documentation',
            field=models.FileField(upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'tiff', 'bmp', 'gif', 'pdf', 'jpg'], message='Тип файла выбран неверно.')], verbose_name='Загрузите результаты диагностического обследования'),
        ),
    ]
