# Generated by Django 4.1.7 on 2023-04-23 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0014_alter_project_documentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='organization_name',
            field=models.CharField(max_length=50, verbose_name='Укажите наименование проектного института'),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.DateField(verbose_name='Укажите дату разработки документации'),
        ),
        migrations.AlterField(
            model_name='sez',
            name='sez_protocol',
            field=models.FileField(upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'tiff', 'bmp', 'gif', 'pdf', 'jpg'], message='Тип файла выбран неверно.')], verbose_name='Загрузите санитарно-экологическое заключение'),
        ),
        migrations.AlterField(
            model_name='sez',
            name='year',
            field=models.DateField(default=None, verbose_name='Укажите дату разработки документации'),
        ),
    ]
