# Generated by Django 4.1.7 on 2023-04-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0015_alter_project_organization_name_alter_project_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_number',
            field=models.IntegerField(null=True),
        ),
    ]
