# Generated by Django 4.1.7 on 2023-04-23 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0016_alter_inventory_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='inventory_ams',
        ),
        migrations.AddField(
            model_name='ams',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ams', to='ams.inventory'),
        ),
    ]
