# Generated by Django 4.1.7 on 2023-04-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0017_remove_inventory_inventory_ams_ams_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
