# Generated by Django 4.1.7 on 2023-04-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0018_alter_inventory_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Укажите краткую характеристику объекта'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Укажите наименование объекта'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Укажите инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='owner',
            field=models.CharField(max_length=50, verbose_name='Укажите организацию'),
        ),
    ]
