# Generated by Django 4.1.7 on 2023-05-01 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0020_alter_ams_passport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurments',
            options={'ordering': ['year']},
        ),
        migrations.AlterField(
            model_name='ams',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'tiff', 'bmp', 'docx', 'pdf', 'doc', 'vsdx'], message='Тип файла выбран неверно.')], verbose_name='Загрузите паспорт АМС'),
        ),
    ]
