# Generated by Django 4.1.7 on 2023-05-07 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0021_alter_measurments_options_alter_ams_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurments',
            name='protocol_pdf',
            field=models.FileField(upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'tiff', 'bmp', 'doc', 'pdf', 'jpg', 'docx'], message='Тип файла выбран неверно.')], verbose_name='Загрузите протокол измерений'),
        ),
        migrations.AlterField(
            model_name='sez',
            name='sez_protocol',
            field=models.FileField(upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'tiff', 'bmp', 'doc', 'docx', 'pdf', 'jpg'], message='Тип файла выбран неверно.')], verbose_name='Загрузите санитарно-экологическое заключение'),
        ),
    ]
