# Generated by Django 4.1.7 on 2023-05-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0022_alter_measurments_protocol_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurments',
            name='is_last',
            field=models.BooleanField(default=False),
        ),
    ]
