# Generated by Django 4.1.7 on 2023-05-26 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_position_district'),
        ('ams', '0024_alter_ams_object_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ams',
            name='object_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ams', to='main.object', verbose_name='Выберите объект'),
        ),
    ]
