from django.urls import path
from . import views

app_name = 'rich'
urlpatterns = [
    path('', views.rich_index, name='rich_index'),
    path('res_create/', views.res_creation, name='res_create'),
    path('res_detail/<int:id>/', views.res_detail, name='res_detail'),
    path('change_name/<int:id>/', views.change_name, name='change_name'),
    path('change_object/<int:id>/', views.change_object, name='change_object'),
    path('change_rich/<int:id>/', views.change_rich, name='change_rich'),
    path('add_rich/<int:id>/', views.add_rich, name='add_rich'),
    path('change_registration/<int:id>/', views.change_registration, name='change_registration'),
    path('add_registration/<int:id>/', views.add_registration, name='add_registration'),
    path('change_radio_class/<int:id>', views.change_radio_class, name='change_radio_class'),
    path('antenna_height_change/<int:id>', views.antenna_height_change, name='antenna_height_change'),
    path('antenna_azimuth_change/<int:id>', views.antenna_azimuth_change, name='antenna_azimuth_change'),
    path('antenna_gain_change/<int:id>', views.antenna_gain_change, name='antenna_gain_change'),
    path('antenna_polarization_change/<int:id>/', views.antenna_polarization_change, name='antenna_polarization_change'),
    path('rich_app_index', views.rich_app_index, name='rich_app_index'),
    path('rich_list', views.rich_list, name='rich_list'),
    path('rich_create', views.rich_create, name='rich_create'),
    path('delete_rich/<int:id>', views.delete_rich, name='delete_rich'),
    path('export_xls_rich', views.export_xls_rich, name='export_xls_rich'),
    path('reg_list', views.reg_list, name='reg_list'),
    path('delete_reg/<int:key>', views.delete_reg, name='delete_reg'),
    path('reg_create', views.reg_create, name='reg_create'),
    path('ajax/load-res/', views.load_res, name='ajax_load_res'),
    path('export_xls_reg/', views.export_xls_reg, name='export_xls_reg'),
    path('res_export_xls/', views.res_export_xls, name='res_export_xls'),
    path('delete_res/<int:key>', views.delete_res, name='delete_res'),
    path('equip_list/', views.equip_list, name='equip_list'),
    path('equip_delete/<int:key>/', views.equip_delete, name='equip_delete'),
    path('equip_create/', views.equip_create, name='equip_create'),
    path('add_equipment/<int:key>/', views.add_equipment, name='add_equipment'),
    path('change_equipment/<int:key>', views.change_equipment, name='change_equipment'),
    path('protokol_list/<int:key>/', views.protokol_list, name='protokol_list'),
    path('protocol_delete/<int:key>', views.protocol_delete, name='protocol_delete'),
    path('add_res_protokol/<int:key>/', views.add_res_protokol, name='add_res_protokol'),
    path('add_res_protokol_list/<int:key>/', views.add_res_protokol_list, name='add_res_protokol_list')
]
