# Generated by Django 4.0.3 on 2023-01-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='res',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
