# Generated by Django 4.0.3 on 2023-01-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rich',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Наименование'),
        ),
    ]
