# Generated by Django 4.0.3 on 2023-01-08 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0002_alter_rich_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='name',
            field=models.CharField(default=1, max_length=30, unique=True, verbose_name='Наименование'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='doc',
            field=models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'tiff', 'bmp', 'gif', 'pdf', 'doc', 'docx'], message='Тип файла выбран неверно.')], verbose_name='Копия свидетельства'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='end_date',
            field=models.DateField(verbose_name='Укажите дату окончания срока действия'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='start_date',
            field=models.DateField(verbose_name='Укажите дату начала действия'),
        ),
    ]
