# Generated by Django 4.0.3 on 2023-01-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0003_registration_name_alter_registration_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Наименование'),
        ),
    ]
