# Generated by Django 4.0.3 on 2023-01-15 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0004_alter_registration_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rich',
            options={'ordering': ['end_date']},
        ),
        migrations.AddField(
            model_name='rich',
            name='is_active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='res',
            name='related_rich',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_res', to='rich.rich', verbose_name='Выберите РИЧ'),
        ),
    ]
