# Generated by Django 4.0.3 on 2023-02-19 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0005_alter_rich_options_rich_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rich',
            options={'ordering': ['-is_active', 'end_date']},
        ),
        migrations.AlterField(
            model_name='res',
            name='related_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_res', to='rich.registration', verbose_name='Выберите регистрацию'),
        ),
    ]
