# Generated by Django 4.0.3 on 2023-02-21 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0007_alter_res_related_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='res',
            name='related_registration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_res_reg', to='rich.registration', verbose_name='Выберите регистрацию'),
        ),
    ]
