# Generated by Django 4.1.7 on 2023-02-25 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0008_alter_res_related_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='res',
            name='related_registration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_res_reg', to='rich.registration', verbose_name='Выберите регистрацию'),
        ),
        migrations.AlterField(
            model_name='res',
            name='related_rich',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_res', to='rich.rich', verbose_name='Выберите РИЧ'),
        ),
    ]
