# Generated by Django 4.1.7 on 2023-02-26 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0010_registration_is_valid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='is_valid',
            new_name='is_active',
        ),
    ]
