# Generated by Django 4.1.7 on 2023-03-01 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0011_rename_is_valid_registration_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='class_res',
        ),
        migrations.AddField(
            model_name='type',
            name='class_name',
            field=models.CharField(choices=[('РРЛ', 'РРЛ'), ('БС конвенциональной связи', 'БС конвенциональной связи'), ('БС транкинговой связи', 'БС транкинговой связи'), ('БС', 'БС'), ('РЭС морской подвижной службы', 'РЭС морской подвижной службы'), ('РЭС сухопутной подвижной службы', 'РЭС сухопутной подвижной службы'), ('Судовые РЭС', 'Судовые РЭС'), ('АС', 'АС')], default=None, max_length=50, verbose_name='класс РЭС'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='res',
            name='antenna_gain',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(50, message='Значение коэффициента усиления антенны не может быть больше 50'), django.core.validators.MinValueValidator(0, message='Значение коэффициента усиления антенны не может быть меньше 0')], verbose_name='Укажите коэффициент усиления антенны'),
        ),
        migrations.AlterField(
            model_name='res',
            name='antenna_height',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(200, message='Значение высоты подвеса антенны не может быть больше 200'), django.core.validators.MinValueValidator(0, message='Значение высоты подвеса антенны не может быть меньше 0')], verbose_name='Укажите высоту установки антенны'),
        ),
        migrations.AlterField(
            model_name='res',
            name='azimuth_value',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(360, message='Значение азимута не может быть больше 360'), django.core.validators.MinValueValidator(0, message='Значение азимута не может быть меньше 0')], verbose_name='Укажите азимут антенны'),
        ),
        migrations.AlterField(
            model_name='res',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='type',
            name='fs_form',
            field=models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.pdf', '.doc', '.docx'], message='Тип файла выбран неверно.')]),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
