# Generated by Django 4.1.7 on 2023-03-01 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0012_remove_type_class_res_type_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='class_name',
            field=models.CharField(choices=[('РРЛ', 'РРЛ'), ('БС конвенциональной связи', 'БС конвенциональной связи'), ('БС транкинговой связи', 'БС транкинговой связи'), ('БС', 'БС'), ('РЭС морской подвижной службы', 'РЭС морской подвижной службы'), ('РЭС сухопутной подвижной службы', 'РЭС сухопутной подвижной службы'), ('Судовые РЭС', 'Судовые РЭС'), ('АС', 'АС')], max_length=50, verbose_name='Выберите класс РЭС'),
        ),
        migrations.AlterField(
            model_name='type',
            name='frequency_range_max',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(90000000000, message='Значение частоты не может быть больше 90 ГГц'), django.core.validators.MinValueValidator(0, message='Значение частоты не может быть меньше 0')], verbose_name='Укажите максимальную частоту обордуования, Гц'),
        ),
        migrations.AlterField(
            model_name='type',
            name='frequency_range_min',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(90000000000, message='Значение частоты не может быть больше 90 ГГц'), django.core.validators.MinValueValidator(0, message='Значение частоты не может быть меньше 0')], verbose_name='Укажите минимальную частоту обордуования, Гц'),
        ),
        migrations.AlterField(
            model_name='type',
            name='fs_form',
            field=models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.pdf', '.doc', '.docx'], message='Тип файла выбран неверно.')], verbose_name='Загрузите форму общих технических данных'),
        ),
        migrations.AlterField(
            model_name='type',
            name='manufacter',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Укажите производителя оборудования'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Введите наименование оборудования'),
        ),
    ]
