# Generated by Django 4.1.7 on 2023-03-05 03:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0013_alter_type_class_name_alter_type_frequency_range_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='fs_form',
            field=models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'], message='Тип файла выбран неверно.')], verbose_name='Загрузите форму общих технических данных'),
        ),
    ]
