# Generated by Django 4.1.7 on 2023-03-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0014_alter_type_fs_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='frequency_str',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
