# Generated by Django 4.1.7 on 2023-03-05 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0015_type_frequency_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='res',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_res', to='rich.type', verbose_name='Укажите тиип оборудования'),
        ),
    ]
