# Generated by Django 4.1.7 on 2023-03-08 05:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0016_res_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='res',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_res', to='rich.type', verbose_name='Укажите тип оборудования'),
        ),
        migrations.CreateModel(
            name='ResProtokol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('doc', models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'tiff', 'bmp', 'gif', 'pdf', 'doc', 'docx'], message='Тип файла выбран неверно.')], verbose_name='Копия разрешения')),
                ('related_res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protokol', to='rich.res')),
            ],
        ),
    ]
