# Generated by Django 4.1.7 on 2023-03-08 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0017_alter_res_type_resprotokol'),
    ]

    operations = [
        migrations.AddField(
            model_name='resprotokol',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='resprotokol',
            name='type',
            field=models.CharField(choices=[('измерения координат', 'измерения координат'), ('измерения высоты подвеса', 'измерения высоты подвеса'), ('измерения параметров РЭС', 'измерения параметров РЭС')], default=None, max_length=50, verbose_name='Выберите тип протокола'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resprotokol',
            name='doc',
            field=models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'tiff', 'bmp', 'gif', 'pdf', 'doc', 'docx'], message='Тип файла выбран неверно.')], verbose_name='Загрузите протокол'),
        ),
    ]
