# Generated by Django 4.1.7 on 2023-03-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich', '0018_resprotokol_name_resprotokol_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resprotokol',
            name='date',
            field=models.DateField(verbose_name='Укажите дату проведения измерений'),
        ),
    ]
