from django.urls import path
from . import views

app_name = 'ams'
urlpatterns = [
    path('', views.ams, name='ams'),
    path('ams_create/', views.ams_create, name='ams_create'),
    path('export_xls_ams/', views.export_xls_ams, name='export_xls_ams'),
    path('delete_ams/<int:ams_id>/', views.delete_ams, name='delete_ams'),
    path('ams_detail/<int:ams_id>/<str:msg>/', views.ams_detail, name='ams_detail'),
    path('ams_detail/<int:ams_id>/', views.ams_detail, name='ams_detail'),
    path('change_height/<int:ams_id>/', views.change_height, name='change_height'),
    path('change_weight/<int:ams_id>/', views.change_weight, name='change_weight'),
    path('change_type/<int:ams_id>/', views.change_type, name='change_type'),
    path('change_date/<int:ams_id>/', views.change_date, name='change_date'),
    path('change_scheme/<int:ams_id>/', views.change_scheme, name='change_scheme'),
    path('delete_scheme/<int:ams_id>/', views.delete_scheme, name='delete_scheme'),
    path('foto_ams_add/<int:ams_id>', views.foto_ams_add, name='foto_ams_add'),
    path('foto_delete/<int:foto_id>/', views.foto_delete, name='foto_delete'),
    path('add_protocol/<int:ams_id>/', views.add_protocol, name='add_protocol'),
    path('add_diagnostic/<int:ams_id>/', views.add_diagnostic, name='add_diagnostic'),
    path('add_project/<int:ams_id>/', views.add_project, name='add_project'),
    path('add_sez/<int:ams_id>/', views.add_sez, name='add_sez'),
    path('add_inventory/<int:ams_id>/', views.add_inventory, name='add_inventory'),
    path('select_inventory/<int:ams_id>', views.select_inventory, name='select_inventory'),
    path('add_passport/<int:ams_id>', views.add_passport, name='add_passport'),
    path('delete_passport/<int:ams_id>/', views.delete_passport, name='delete_passport'),
    path('project_list/<int:ams_id>/', views.project_list, name='project_list'),
    path('project_list/<int:ams_id>/<str:msg>/', views.project_list, name='project_list'),
    path('project_delete/<int:project_id>/', views.project_delete, name='project_delete'),
    path('add_project_list/<int:ams_id>/', views.add_project_list, name='add_project_list'),
    path('do_list/<int:ams_id>/', views.do_list, name='do_list'),
    path('do_list/<int:ams_id>/<str:msg>/', views.do_list, name='do_list'),
    path('do_delete/<int:do_id>/', views.do_delete, name='do_delete'),
    path('add_do_list/<int:ams_id>/', views.add_do_list, name='add_do_list'),
    path('measurement_list/<int:ams_id>/', views.measurement_list, name='measurement_list'),
    path('measurement_list/<int:ams_id>//<str:msg>', views.measurement_list, name='measurement_list'),
    path('measurement_delete/<int:measurement_id>/', views.measurement_delete, name='measurement_delete'),
    path('add_measurement_list/<int:ams_id>/', views.add_measurement_list, name='add_measurement_list'),
    path('sez_list/<int:ams_id>/', views.sez_list, name='sez_list'),
    path('sez_list/<int:ams_id>/<str:msg>', views.sez_list, name='sez_list'),
    path('sez_delete/<int:sez_id>/', views.sez_delete, name='sez_delete'),
    path('add_sez_list/<int:ams_id>/', views.add_sez_list, name='add_sez_list'),
    path('foto_list/<int:ams_id>/', views.foto_list, name='foto_list'),
    path('foto_list/<int:ams_id>/<str:msg>/', views.foto_list, name='foto_list'),
    path('foto_list_delete/<int:foto_id>', views.foto_list_delete, name='foto_list_delete'),
    path('add_foto_list/<int:ams_id>/', views.add_foto_list, name='add_foto_list')
    ]
